name: finvest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  # to show snackbar on the screen
  another_flushbar: ^1.10.29
  # bloc dependencies
  bloc_concurrency: ^0.2.1
  # to cache the images locally
  cached_network_image: ^3.2.3
  # connectivity -- Network connection checkup
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  # dartz -- For Union/Map etc
  dartz: ^0.10.1
  # dio -- To handle http network call
  dio: ^5.0.2
  # to show the graph view
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  # for adaptive screen and font size
  flutter_screenutil: ^5.6.0
  # for showing loader
  flutter_spinkit: ^5.1.0
  # to handle svg in the app
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  # To give gap between two widgets
  gap: ^3.0.0
  # to handle injection
  get_it: ^7.2.0
  # http -- dio depends on it
  http: ^1.2.2
  injectable: ^2.4.4
  # json annotation -- to be used with json serialization
  json_annotation: ^4.8.0
  # to show the beautiful logs in console
  logger: ^1.1.0
  # rxdart for reactive programming
  rxdart: ^0.27.2
  # shimmer effect loading
  shimmer: ^2.0.0
  # meta for some more support
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/